### ISSUE TITLE
Purpose of the 'id' field for calendars (documentation)

### ISSUE THREAD

**Issue by Louis-Aime** [tc39/proposal-temporal#1126]
What is finally the role of the `id` field when constructing a `new Temporal.Calendar(id)` ?

- if you construct a calendar with `new Temporal.Calendar(id)`, the string passed to the constructor must be one of the names of the built-in calendars. What is the rationale ? In the polyfill, I constructed the Julian calendar as well as a class for western calendars with different transition dates to gregory. Having a same 'id' is very confusing when I read a date like `"-000752-04-13[c=gregory]"`, I would prefer to read `"-000752-04-13[c=julian]"` to express that this date should be projected in the Julian calendar, i.e. 21 April 753 B.C.
- I constructed another calendar as a plain object. I defined it as 'milesian'. I found no difficulty in doing this with respect to the subclassed one. Why is it forbidden just to subclass and define a new name ?

Are you saying that if you subclass, you may omit most methods, just override those you need, e.g. weekOfYear if you use another numbering system, or maybe year, month, day and daysInMonth if you want to implement a small variant like the Swedish calendar from 1700 to 1712 ?

IMHO some more explanation or examples would help the calendar's author to make its choice.

**Comment by ptomato** [comment]
`new Temporal.Calendar(id)` does only accept the names of built-in calendars. This is because there cannot be a user-modifiable "registry" of calendars. The closest you can get is overriding `Temporal.Calendar.from()` which will allow you to construct dates from strings like `-000752-04-13[c=julian]`

To get the correct `[c=julian]` annotation to appear when printing out dates, your custom calendar must override the `toString()` method. Subclassing a calendar and defining a calendar as a plain object should be equivalent, so I think overriding `toString()` was probably what your Julian calendar was missing relative to your Milesian calendar.

It is correct that when subclassing, you may omit methods that you don't need. Note that when you subclass you have to pass the ID of the calendar that you are deferring to in the `super()` call in the constructor, as well as override `toString()` in your subclass. This is intended to be fixed/clarified in #847.

I will close this issue but will make sure that all of this is clarified in the documentation in #1127, thanks.
