### ISSUE TITLE
Delegate review: Daniel Ehrenberg

### ISSUE THREAD

**Issue by ptomato** [tc39/proposal-temporal#1384]
Thread for discussions / signing off from designated reviewer @littledan, in preparation for Stage 3

**Comment by littledan** [comment]
(Just to get it out of the way: I'm quite a biased reviewer, as I've been mentoring some of the champions, and my work is sponsored by Bloomberg here.)

Overall, I'm very happy with the API that this proposal exposes, and the detailed work in the documentation and polyfill. This API is really regular and predictable, and hopefully should be easy to use for JavaScript developers to help them avoid bugs and internationalize their applications.

The main thing that stood out for me in review was the complexity of the Calendar and TimeZone protocols, which I fear could be difficult to optimize. I suspect that many important use cases could be met by a lower-level/less expressive protocol. I'd like to investigate this issue further between Stage 3 and 4 in the context of an actual engine implementation, which will give us more information here. https://github.com/tc39/proposal-temporal/issues/1432

I didn't yet find any further issues or nits beyond what others have already posted (maybe because I didn't do a thorough enough review). I plan to keep reviewing for this purpose. The proposal seems good to go to Stage 3 as far as I can tell, though.
