### ISSUE TITLE
Improve documentation arguments, mainly changing "thing: any"

### ISSUE THREAD

**Issue by jasonwilliams** [tc39/proposal-temporal#1394]
Looking at https://tc39.es/proposal-temporal/docs/instant.html#from for example, i don't find the `(thing: any)` very helpful. I think we can do better here to help users understand what is being passed in. The example below shows only a string being used so why is thing's type not `string`? Well thats because you can also pass an Instant according to the type declaration.
 
So maybe we need to match the docs up with the type declarations more? like `Temporal.Instant | string`

**Comment by ptomato** [comment]
I guess the uncertainty here is due to the discrepancy between what the function technically accepts and what is recommended to pass. For example, you can pass a number (this actually works in `Temporal.PlainDate.from(20210302)`) or an object (`{ valueOf() { return '2021-03-02T20:29Z'; }}`) and they will get converted to strings. But, of course nobody should do this, so it's probably better to document the recommended usage.
