### ISSUE TITLE
Question? There a cjs version of this polyfill somewhere?

### ISSUE THREAD

**Issue by chrisjlee** [tc39/proposal-temporal#1466]
Trying to get this to work and run the cookbook examples is there a way i can get a compiled version of this to prototype in a sandbox website codepen, etc?

Also, is there a repl somewhere to try this stuff out?

I'm not given permission to install any npm packages; it has to be approved.

**Comment by ptomato** [comment]
Hi, you can get a REPL by going to the [reference documentation](https://tc39.es/proposal-temporal/docs/index.html) and opening the developer console in your browser, where the Temporal polyfill will be already loaded. [RunKit](https://npm.runkit.com/proposal-temporal) also automatically generates sandbox environments for all published NPM packages.

If you can't install npm modules locally to build, then you can probably grab the [compiled version from the documentation page](https://tc39.es/proposal-temporal/docs/playground.js) Although note that the documentation sandbox does have debug features enabled, and includes code to install itself onto the global object, which we otherwise discourage doing automatically.
