### ISSUE TITLE
Change (non-normative) spec to prefer singular over plural variants of unit option values

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#1488]
Followup from https://github.com/tc39/proposal-temporal/issues/325#issuecomment-820606460: 
* **The spec may be changed to prefer internal use of the singular variant of option values.**  Note that this is not a normative change because there will be no observable impact to callers.

**Comment by ptomato** [comment]
This is handled as part of #1491 and #1509 already. The reason is because in some cases we would need to pass the option value to user code in `Calendar.dateUntil()`, it would actually be more churn to implement this non-normatively first and then normatively. #1491 and #1509 achieved consensus in today's TC39 meeting, so closing this.
