### ISSUE TITLE
Why is master called main now?

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#153]
`master` is a long-standing convention; changing it seems to only add unnecessary friction for contributors.

**Comment by michalDob** [comment]
https://medium.com/@mikebroberts/let-s-stop-saying-master-slave-10f1d1bf34df <- the reason in a nutshell

but I totally agree this language is in common usage and is not going away, no reason to create confusion

**Comment by pipobscure** [comment]
Yep @michalDob & @Ms2ger that's the reason. Someone flagged it explicitly and I didn't want to engage in that discussion. Much easier to just change the branch-name and be part of the solution rather than the problem.

Plus I don't buy the *long-standing convention* argument. The same can be said for the n-word and many other things. Not particularly convincing to me.
