### ISSUE TITLE
Decide on hyphen vs minus for negation/subtraction

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#1548]
We currently use both.

**Comment by ljharb** [comment]
Pretty sure the spec uses a normal `-` (en dash) for negation/subtraction; i'm not sure why we'd use anything else.

**Comment by ptomato** [comment]
It seems to use a - (hyphen) in almost all cases, and one instance of − (minus sign). There is one instance of – (en dash) used for a range of numbers.

I feel like if it's preferred to use × (times symbol) for multiplication and not * (asterisk) or x (letter) then the minus sign is more correct, but it's pretty much visually indistinguishable from an en dash, so I don't care other than for semantic reasons.

The use of hyphens seems like it would be nice to fix, though, since we have periodically been talking about [a professionally typeset version of Ecma-262](https://github.com/tc39/notes/blob/886ead863abbef6c7546c97c36e0fae7aba8dc8d/meetings/2021-04/apr-19.md#secretary-report) and after all the equations I've typeset in my life the hyphen looks quite wrong to me :smile:

**Comment by ljharb** [comment]
Ah oops, i got confused, i meant hyphen :-)

**Comment by ljharb** [comment]
We could likely make ecmarkup change the hyphen into a different character if it can be statically determined by the context.

**Comment by gibson042** [comment]
It is not explicitly documented, but the operator for subtraction is `-` (U+002D HYPHEN-MINUS), for multiplication is `&times;` (encoding U+00D7 MULTIPLICATION SIGN), and for division is `/` (U+002F SOLIDUS)—cf. https://github.com/tc39/ecma262/pull/2730#issuecomment-1106582484 .
