### ISSUE TITLE
Documentation: two small improvements

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-temporal#1559]
I hope that this is the right channel for this kind of feedback:

* Typo: `Intl.ZonedDateTimeFormat` in https://tc39.es/proposal-temporal/docs/zoneddatetime.html
* Suggestion for the cookbook: Mention “cookbook” in `<title>Temporal documentation</title>`
  * Why? Better title for tab.

**Comment by justingrant** [comment]
> I hope that this is the right channel for this kind of feedback:

Yep, you found the right place!

> * Typo: `Intl.ZonedDateTimeFormat` in https://tc39.es/proposal-temporal/docs/zoneddatetime.html

Thanks for finding this bug! #1562 will fix it. 

> * Suggestion for the cookbook: Mention “cookbook” in `<title>Temporal documentation</title>`

We're not going to change page-level info like this because the current Temporal docs are in process of being migrated to MDN where there are different pagewide standards. I assume that MDN page titles will be context-sensitive, but @meyerweb can speak to that better than I can.
