### ISSUE TITLE
Temporal Polyfill: wrong import statement in readme?

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-temporal#1577]
[The readme](https://github.com/tc39/proposal-temporal/blob/main/polyfill/README.md) recommends:

```js
import { Temporal } from 'proposal-temporal/lib/index.mjs';
```

However, that didn’t work for me. This did:

```js
import {Temporal} from 'proposal-temporal';
```

Interestingly, the tests use this import statement (which didn’t work for me, either):

```js
import * as Temporal from 'proposal-temporal';
```

**Comment by ptomato** [comment]
Strange. I wonder if this changed sometime between Node 12.x to 16.x, as I'm pretty sure that didn't work when I wrote that. Anyway, since the polyfill is being deprecated we'll be removing those instructions soon. The tests use a different mechanism (module loader) but are gradually being converted to test262 tests. So I think we'll probably not change anything at this point.
