### ISSUE TITLE
Should Date.withTime have a disambiguation argument?

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#179]
@pipobscure said no in https://github.com/tc39/proposal-temporal/pull/161/files#r333621271, but the polyfill has it:

https://github.com/tc39/proposal-temporal/blob/3a51ea6e5cb697ed55c44531106d47b0b03fc468/polyfill/lib/date.mjs#L108-L116

**Comment by pipobscure** [comment]
I am inconsolably inconsistent.

The reason for this is that originally we allowed only property Time instances as arguments to this method. In which case disambiguation is not necessary, since the argument is perforce consistent.

However we have since changed that to allow pretty much anything that can be cast to a timeLike value. At which point disambiguation does become relevant.

However since Casting can actually be done, I wonder whether we should just reject inconsistent values and require casting if needed. But then again it;s a hassle.

You see the conundrum?
Your thoughts are as good as mine.
Opinions?
