### ISSUE TITLE
ECMA-402 should allow numeric-offset host time zones

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-temporal#1922]
Among other things, this would remove the need to override ECMA-262 DefaultTimeZone.

**Comment by ptomato** [comment]
Should this be a discussion over at tc39/ecma402 instead?

**Comment by gibson042** [comment]
I'm considering it a change that would be part of Temporal, but if it makes more sense to discuss there then that's fine.

**Comment by ptomato** [comment]
I think all the necessary changes on the Temporal side are in https://github.com/tc39/proposal-temporal/pull/2171.

In ECMA-402 they would then delete their override of DefaultTimeZone and ensure that all of its callers are prepared to deal with a numeric-offset time zone. I think that further discussion should be had over there, because it doesn't affect Temporal.
