### ISSUE TITLE
Review subclassing support

### ISSUE THREAD

**Issue by Ms2ger** [tc39/proposal-temporal#196]
In #195, @littledan suggested that `Duration.fromNanoseconds` and friends should be able to return subclasses of `Duration`. This seems somewhat reasonable, but we should consider what happens in other subclassing cases. For example, what happens to `Time.withDate`? Is there any way that can return a subclass of `DateTime`? How? If not, do we want to support that by replacing it with `DateTime.from`?

**Comment by ljharb** [comment]
If a static method on X produces an X, then that same method called on Y (which extends X) should produce an instance of Y.

It doesn’t seem necessary for a static method on X that produces an A to be able to produce subclasses of A, since there’s no obvious place to get the subclass from.

An example might be Array.from, which respects subclassing; versus Object.keys and friends, which offer no mechanism to produce a subclass of an Array.
