### ISSUE TITLE
The 'gregory' calendar gives a Era error

### ISSUE THREAD

**Issue by JulianKragt** [tc39/proposal-temporal#2020]
In Firefox 96 i get another error.
`Era a (ISO year 2020) was not matched by any era`

![Screenshot from 2022-01-26 17-02-43](https://user-images.githubusercontent.com/18495180/151199679-4055c0fc-ea68-4a18-af53-da22b3e48665.png)

This is working in firefox 96.
```javascript
Temporal.PlainDate.from({year: 2020, month: 1, day: 1}).withCalendar('gregory');
```
but this is giving the Era error.
```javascript
Temporal.PlainDate.from({year: 2020, month: 1, day: 1, calendar: 'gregory'});
```

in the function completeEraYear in file calendar.mjs. `// line 1443`

completeEraYear runs 3 times. (why is it even running 3 times?)
first and second runs gets it data from eraFromYear.
eraFromYear returns the created data correctly.

but the third run because calendarDate.year is gone and replaced with calendarDate.era.
because calendarDate.year is gone it wont run eraFromYear.
so it checks if 'era' in calendarDate is a valid. 
but calenderDate.era returns 'a', that isn't a valid era.

each object is calendarDate in a new run.
![Screenshot from 2022-01-26 16-28-57](https://user-images.githubusercontent.com/18495180/151193282-a8631d8e-e407-46f2-9c5b-f41853cab437.png)

so somewhere it sets era to be 'a'
i can't find it.

_Originally posted by @Julpower31 in https://github.com/tc39/proposal-temporal/issues/2015#issuecomment-1022009485_

**Comment by justingrant** [comment]
Sigh. The bug is with FF 96's `era: 'short'` representation which is what the polyfill currently uses for all locales except Japanese where `'short'` values are ambiguous and the full era name is needed.  Anyway, `'gregory'` era in the short format should be `'AD'`, not `'A'`.  In fact, this is even an example in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat)! 

![image](https://user-images.githubusercontent.com/277214/151240226-cdfb37ef-d672-4bc8-9490-b5c1ced45a34.png)

I'll follow up with another FF bug for this. Here's the repro: 
```js
dtf = new Intl.DateTimeFormat(`en-US-u-ca-gregory`, {
  day: 'numeric',
  month: 'numeric',
  year: 'numeric',
  era: 'short',
  timeZone: 'UTC'
});
parts = dtf.formatToParts(new Date('2019-02-06T00:00Z'));
parts.filter(p => p.type === 'era')[0];
```

Thanks so much for finding these bugs!  It's a challenge because the output of DateTimeFormat is not something that's covered the ECMA 402 (Internationalization) spec; the values are obtained from Unicode CLDR and the accuracy of that data is not always perfect. Also, AFAIK Firefox 96 landed a big internal refactor of DateTimeFormat so it's not surprising that we're seeing bugs like this where the old implementation handled it correctly but the new one is different.

Thanks again!
