### ISSUE TITLE
Will the existing Islamic (Hijri) Calendar Date Discrepancy be Fixed in Temporal

### ISSUE THREAD

**Issue by MohsenAlyafei** [tc39/proposal-temporal#2042]
There is a discrepancy in conversion/output of the Islamic (Hijri) Calendar Date in the current javascript method between `islamic` and `ar-SA` although the `ar-SA` locale uses the islamic (hijri) calendar by default.

Please see here on Stackoverflow:

https://stackoverflow.com/questions/70996839/discrepancy-in-javascript-intl-datetimeformat-outputs-for-the-islamic-hijri

I hope this will be avoided/fixed in temporal.

Thanks

**Comment by justingrant** [comment]
Hi @MohsenAlyafei - I responded in detail over in Stack Overflow. https://stackoverflow.com/questions/70996839/discrepancy-in-javascript-intl-datetimeformat-outputs-for-the-islamic-hijri/71004938#71004938

Note that Temporal does not implement calendar calculations; all calculations are delegated to a single shared implementation that's is used by `Temporal.*.prototype.toLocaleString`, `Date.prototype.toLocaleString`/`Date.prototype.toLocaleDateString`, and `Intl.DateTimeFormat`.  The parameters and options also match between those  methods.  So if there's a problem with a specific Gregorian->Islamic conversion, Temporal can't fix it. Instead, the [ECMA 402 repo](https://github.com/tc39/ecma402) is a good place to file issues because the folks who actually own the spec and the implementation are maintainers there. 

But before filing issues, please try the time zone and calendar-variation solutions in my Stack Overflow answer. I suspect one or both of those will resolve the issue that you're encountering.

I'm going to close this issue for now because I think your question is resolved over in Stack Overflow, and also because the Temporal repo isn't the right repo for calendar calculation issues.
