### ISSUE TITLE
Does temporal support for query monotonic nanosecond current time?

### ISSUE THREAD

**Issue by lygstate** [tc39/proposal-temporal#2048]

**Comment by lygstate** [comment]
> Temporal doesn't provide a monotonic clock. For monotonic time measurements, you need to be on a platform that supports `performance.now()` (although you can take a monotonic measurement in nanoseconds and store it in `Temporal.Duration` if you want to perform further manipulations on that value.)

I would suggest add `Temporal.Now.monotonic()` api to retrieve of monotonic nanosecond current time

**Comment by justingrant** [comment]
Hi @lygstate - What use case(s) do you have in mind for a monotonic timer API?

Also, are you looking for the same behavior as the existing [`Performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) API, just with a different name?  Or are you expecting different behavior, and if so what?

**Comment by lygstate** [comment]
> Hi @lygstate - What use case(s) do you have in mind for a monotonic timer API?
> 
> Also, are you looking for the same behavior as the existing [`Performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) API, just with a different name? Or are you expecting different behavior, and if so what?

* https://developer.mozilla.org/en-US/docs/Web/API/Performance/now is for Web only, not for Javascript
* The precision of Performance.now() is microseconds, not nanoseconds
* When I am trying to measure nanosecond precision time duration, it's not possible with `Performance.now()`

**Comment by ptomato** [comment]
I think it's unlikely that browsers would agree to standardize nanosecond precision measurements as part of JS, for security reasons.

But like Justin, I'm still curious about what your use case is! It seems that this use case:
- is on a platform other than a browser? (And I'm guessing also not Node.js, where you could use `process.hrtime()`?)
- requires nanosecond accuracy, microseconds is not sufficient?

**Comment by justingrant** [comment]
> I think it's unlikely that browsers would agree to standardize nanosecond precision measurements as part of JS, for security reasons.

If you're unfamiliar with these security issues, here's a good post for context: https://v8.dev/blog/spectre.

Note that these security issues are not only limited to browsers but apply to any environment where sandboxing is used and/or multiple users' code is being executed in the same process. For example, Cloudflare Workers [prevents time measurement](https://blog.cloudflare.com/mitigating-spectre-and-other-security-threats-the-cloudflare-workers-security-model/#step1disallowtimersandmultithreading) by fixing the value of `Date.now` (and presumably any other timing APIs). Timing APIs will return the same value during the execution of any particular Worker's execution, making it impossible to measure elapsed time in a Worker.

So ultimately the resolution of timers will be decided by wherever the code is being executed, not by the ECMAScript spec.

> * (And I'm guessing also not Node.js, where you could use `process.hrtime()`?)

If the issue is purely about wanting to have a common API across both Node and browsers, then I suspect that the right solution would be to try to get the `Performance` object into Node, kinda like how `fetch` was just added to Node 17.

**Comment by ptomato** [comment]
I think the question is answered, so closing.
