### ISSUE TITLE
PlainYear to complement PlainYearMonth and PlainDate

### ISSUE THREAD

**Issue by thewilkybarkid** [tc39/proposal-temporal#2359]
I'm currently working with an HTTP API that might return a date, a year–month combination or just a year by itself.

I'm turning them into the type:

```ts
type PartialDate = number | PlainYearMonth | PlainDate
```

(https://github.com/thewilkybarkid/crossref-ts/blob/2ae08e578e344e14864a0dbdce73ae6834c58bef/src/index.ts#L56)

This isn't ideal as a year by itself isn't strongly typed nor provides a `toLocaleString` function.

(I can work around the latter by turning it into a `PlainYearMonth` and then using the `{ year: 'numeric' }` option to ignore the fake month.)

An equivalent object exists in other languages, e.g. [`java.time.Year`](https://docs.oracle.com/javase/8/docs/api/java/time/Year.html).

I can only find [one reference to a `PlainYear` object](https://github.com/tc39/proposal-temporal/blob/40c36f9bd2a187a6202ce6f702966eec2ed07716/meetings/agenda-minutes-2021-01-19.md#spicy-option-5), but that seems to have been referenced in a different context (#1203).

Has such a type been discussed, and, if not, is it too late to consider it?

**Comment by ptomato** [comment]
It's too late to consider it for the version of Temporal that is now being implemented in browsers.

Also I think this is not quite a straightforward addition. There would be design work required for how it would interact with eras and other year-related fields from non-Gregorian calendars. (The Java object is explicitly only a numerical year from an ISO 8601 calendar.)

I do get the point that Number's `toLocaleString` is not appropriate for locale-aware formatting of years:
```js
> (2022).toLocaleString()
'2,022'
> Temporal.Now.plainDateISO().toLocaleString(undefined, {year: 'numeric'})
'2022'

> (-1).toLocaleString()
'-1'
> Temporal.PlainDate.from({year: -1, month: 7, day: 14}).toLocaleString(undefined, {year: 'numeric', era: 'short'})
'2 BC'
```

For now, I would recommend continuing to do what you are doing, or rolling your own PlainYear type, which could be calendar-aware or ISO-only, depending on what your application needs. If it can be ISO-only then you might get away with something as simple as this:
```js
// note: untested
class PlainYear {
  #isoYear;
  constructor(isoYear) {
    this.#isoYear = isoYear;
  }
  valueOf() {
    return this.#isoYear;  // so you can pass it in property bags to other Temporal types
  }
  toString() {
    return this.#isoYear.toString();
  }
  toLocaleString(locales, options) {
    const irrelevantOptions = ['weekday', 'month', 'day', 'timeZoneName'];
    options = Object.fromEntries(Object.entries(options).filter(([key]) => !irrelevantOptions.includes(key)));
    options.calendar = 'iso8601';
    return Temporal.PlainDate.from({ year: this.#isoYear, month: 1, day: 1 }).toLocaleString(locales, options);
  }
}
```

I'll close this now, but would you consider opening a new issue in https://github.com/js-temporal/proposal-temporal-v2 using the "feature proposal" template? (Sorry I can't transfer it directly because the repos belong to different organizations.)
