### ISSUE TITLE
Loop output the current date, why the nanometers do not change

### ISSUE THREAD

**Issue by qcyblm** [tc39/proposal-temporal#2372]
``` js
for (let i = 0; i < 5; i++) {
  console.log(Temporal.Now.zonedDateTimeISO("Asia/Shanghai").toString());
}
/*
2022-08-09T11:17:30.784660015+08:00[Asia/Shanghai]
2022-08-09T11:17:30.786660015+08:00[Asia/Shanghai]
2022-08-09T11:17:30.787660015+08:00[Asia/Shanghai]
2022-08-09T11:17:30.788660015+08:00[Asia/Shanghai]
*/
```

**Comment by justingrant** [comment]
The polyfill used in the Temporal docs (which is not for production use) as well as [@js-temporal/polyfill](https://www.npmjs.com/package/@js-temporal/polyfill) (which is intended for production use) both currently use `Date.now()` to power the values returned by `Temporal.Now` methods.  

This means that these current polyfills are only really accurate to the millisecond. For testing, and to make results more realistic-looking, microseconds and nanoseconds are faked by the polyfill using this code:
https://github.com/tc39/proposal-temporal/blob/f47d57d91dfd3601f226a7784d3fa74a6b121dca/polyfill/lib/ecmascript.mjs#L4745-L4756

A native (non-polyfilled) Temporal implementation will likely be somewhat more precise, but you shouldn't expect nanoseconds to be accurate there either because browsers and JS engines (and, for cloud providers, underlying OSs too!) are likely configured to avoid very high-res timers to avoid the risk of SPECTRE and other related speculative-execution hacks. You can see this by running `performance.now` (high-res timer) in a loop and you'll see similar results, where the same values are returned many times in a row before the value increments by 1-3 tenths of a millisecond. 
```js
for (let i = 0; i < 100; i++) {
  console.log(performance.now());
}
```
