### ISSUE TITLE
PlainMonthDay/PlainYearMonth `toPlainDate` doesn't accept an ISO string. Expected?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#2464]
While answering Frank's question in https://github.com/tc39/ecma402/issues/741, I found something that I think might be a bug: the `toPlainDate` additive conversion methods of `PlainMonthDay`/`PlainYearMonth` don't accept ISO strings, but do accept Temporal instances and property bags.

This behavior seems contrary to the general principle that anywhere you can pass a Temporal instance, you can also pass an ISO string or a property bag. There was some discussion of this case in [#889](https://github.com/tc39/proposal-temporal/issues/889#issuecomment-714531077), but I didn't see anything in #889 that said that we decided to omit ISO strings here.

```js
// these lines throw: TypeError: argument should be an object
Temporal.PlainMonthDay.from({ month: 12, day: 25 }).toPlainDate('2020-01-01');
Temporal.PlainYearMonth.from({ month: 12, year: 2022 }).toPlainDate('2020-01-01');

// these lines don't throw
Temporal.PlainMonthDay.from({ month: 12, day: 25 }).toPlainDate(Temporal.PlainDate.from('2020-01-01'));
Temporal.PlainYearMonth.from({ month: 12, year: 2022 }).toPlainDate(Temporal.PlainDate.from('2020-01-01'));
Temporal.PlainMonthDay.from({ month: 12, day: 25 }).toPlainDate(Temporal.PlainDate.from({ year: 2020, month: 1, day: 1 }));
Temporal.PlainYearMonth.from({ month: 12, year: 2022 }).toPlainDate(Temporal.PlainDate.from({ year: 2020, month: 1, day: 1 }));
```

**Comment by ptomato** [comment]
Temporal instances may be supported incidentally here because they are technically Objects with a `day` property, but I don't think passing a full date to PMD.toPlainDate or PYM.toPlainDate is a use case that makes sense. What should a user even expect from `monthDay.toPlainDate('2020-01-01');`?

I'm strongly against expanding the scope of the proposal based on a concern that doesn't come from implementation / field experience.

If we had a PlainYear / PlainDay type with an associated string representation, it'd be a different story, because that's semantically what these methods take.
