### ISSUE TITLE
callback for seconds transition

### ISSUE THREAD

**Issue by flip111** [tc39/proposal-temporal#2487]
I couldn't find it in the docs or cookbook.

Could the API provide a function which takes a callback which is called exactly when the datetime goes to the next second? Many implementations use `setInterval` with 1000 ms, but this is not ideal.

**Comment by justingrant** [comment]
Thanks for the suggestion. [`setInterval`](https://developer.mozilla.org/en-US/docs/Web/API/setInterval) is actually part of the Web API (implemented by browsers and other hosts), not in ECMAScript itself. So any changes to it (and similar APIs like the one you propose) would therefore happen over in that part of the web platform, not in ECMAScript. 

If you wanted to build such an API yourself, it shouldn't be that hard. Here's one quick example. 

```js
function setEverySecond(callback) {
  let cancelled = false;
  const innerCallback = () => {
    if (cancelled) return;
    callback();
    setTimeout(innerCallback, 1000 - (Date.now() % 1000));
  }
  setTimeout(innerCallback, 1000 - (Date.now() % 1000));
  return () => {
    cancelled = true;
  }
}

let calls = 0;
const clearEverySecond = setEverySecond(() => {
  console.log(`${++calls} calls at ${new Date()}`);
  if (calls >= 5) clearEverySecond();
});
```

Because this request is out of scope to Temporal, I'm going to close this issue now.
