### ISSUE TITLE
DifferenceISODateTime no longer needs to copy the "options" object

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2525]
The `options` is already a copy of an user-supplied options object (cf. #2447), so it's no longer necessary to copy the `options` object in DifferenceISODateTime.

**Comment by ptomato** [comment]
I think it's probably still a best practice for DifferenceISODateTime to copy the object before modifying its `largestUnit` property. (Even though currently, nothing happens to re-use the object after it's been passed to DifferenceISODateTime.)

But I can tighten the type assertions in DifferenceISODateTime, and use `! SnapshotOwnProperties(...` instead of `? SnapshotOwnProperties(? GetOptionsObject(...`
