### ISSUE TITLE
ToFractionalSecondDigits: floor or truncate? 

### ISSUE THREAD

**Issue by anba** [tc39/proposal-temporal#2528]
#2437 reverted #2297 by replacing `truncate` with `floor`. Was this intentional?

**Comment by sffc** [comment]
Related:

- https://github.com/tc39/proposal-temporal/pull/2437#discussion_r1036201483
- https://github.com/tc39/ecma402/issues/691

**Comment by gibson042** [comment]
Intentional but plausibly misguided in light of https://github.com/tc39/ecma402/issues/691 in particular.

**Comment by ptomato** [comment]
Discussed in the champions meeting of 2023-04-27. There is existing inconsistency between ECMA-262 (e.g. `Number.prototype.toFixed` truncates then validates range) and ECMA-402 (DefaultNumberOption validates range then floors) as detailed in tc39/ecma402#691. Ideally we'd like alignment everywhere, but in the absence of that, the current behaviour of `fractionalSecondDigits` in Temporal seems best because:
- it's the behaviour we'd design if starting from scratch: e.g., `fractionalSecondDigits: -0.1` throws and we think this is good;
- it's the most conservative option, so if aligning the behaviour was agreed upon in the future, changing it in ToFractionalSecondDigits would bring less web compatibility risk.
