### ISSUE TITLE
when will this proposal move to stage 4

### ISSUE THREAD

**Issue by aliibrahim123** [tc39/proposal-temporal#2636]

**Comment by ptomato** [comment]
Hi! Glad to hear you are interested in using Temporal.

The people monitoring this issue tracker can't make any guarantees about when the proposal will move to stage 4, because a lot of it is out of our hands. It depends on when the browsers prioritize the work of implementing it, because one of the entrance requirements for stage 4 is "Two compatible implementations which pass the acceptance tests", and there are other nontrivial requirements as well. See https://tc39.es/process-document/ for the full list.

For the immediate next steps, you can monitor issue #2628.
