### ISSUE TITLE
Add Temporal.*.now() wrapper methods equivalent to Temporal.Now.*

### ISSUE THREAD

**Issue by rnarkk** [tc39/proposal-temporal#2676]
Hi. Can we add .now() methods to each temporal type as they are more intuitive when instantiating types?

For example, instead of `Temporal.Now.plainDateTime`, I want to write like `Temporal.PlainDateTime.now()`.

Rust's chrono crate is a good API design reference: https://docs.rs/chrono/latest/chrono/.

**Comment by justingrant** [comment]
Hi @rnarkk - Thanks for the suggestion! Temporal is currently in Stage 3 so any new features added to it would require a new proposal. There's a feedback repo https://github.com/js-temporal/proposal-temporal-v2 that you can use to submit suggestions for new Temporal APIs.

Note that the current design, which I agree is less ergonomic than `now` methods, was used because makes it easier to control access to the current system time and time zone. Here's more context about why this matters:

There are host environments that want to remove access of ECMAScript code to know the current system time and/or time zone. These include:
* For security reasons, some hosts like [Cloudflare Workers](https://developers.cloudflare.com/workers/learning/security-model/#step-1-disallow-timers-and-multi-threading) don't want to allow users to measure how long it takes to run ECMAScript code.
* In addition to the security benefits, some host environments want to ensure results are always deterministic. For a database, determinism improves performance (especially for transactions) because intermediate results never need to be persisted. Instead, if a function fails for whatever reason (e.g. out of memory, system crash, etc.) then the function can simply be restarted without worrying about the results being different. This has big advantages for a distributed system. For example, the host environment can divide up a huge transaction across multiple physical nodes and will never have to roll back the entire transaction if one node fails. Instead, the work can simply be given to another node.

Anyway, that's why some host environments want to disable or override access to the current time. `Temporal.Now` provides a single place where those environments can lock down all access to the current time.  This works for all future ECMAScript code, even if ECMAScript adds more Temporal objects. 

However, if each Temporal type had a `now` method, then:
* An existing userland lockdown script or polyfill would not know which method to lock down if a new Temporal type is added.
* Locking down entire objects is AFAIK easier (and has fewer side effects) compared to locking down individual methods.
* It's harder to identify code that uses the current date & time via static analysis, e.g. using ESLint rules.

It's possible that those limitations may be overcome or may matter less in the future, so feel free to add your suggestion to the https://github.com/js-temporal/proposal-temporal-v2 repo, or even to try starting a new TC39 proposal if you're so inspired.
