### ISSUE TITLE
 GetTemporalOverflowOption(options) looks redundant in 9.2.2

### ISSUE THREAD

**Issue by jasonwilliams** [tc39/proposal-temporal#2920]
In Boa we've been implementing plainYearMonth, I've noticed that in  https://tc39.es/proposal-temporal/#sec-temporal.plainyearmonth.from we check if an item passed in is a PlainYearMonth and if it is take the values from it and create a new one.  

However we first call [GetTemporalOverflowOption](https://tc39.es/proposal-temporal/#sec-temporal-gettemporaloverflowoption) but then don't do anything with the value, this looks like a mistake, should it be throwing if the options are invalid or should that line be removed, the next line after (b) doesn't use the value produced from options at all.

[PlainMonthDay](https://tc39.es/proposal-temporal/#sec-temporal.plainmonthday.from) does the same thing, plus in the [toTemporalMonthDay](https://tc39.es/proposal-temporal/#sec-temporal-totemporalmonthday) operation item 10

**Comment by ptomato** [comment]
We discussed this in chat but for everyone else following along: this has raised eyebrows before, but it's intentional. If you pass `{ overflow: 'kjfdhgkfdshgkdj' }` it should throw regardless of whether you take the property bag path or the string path, even though overflow doesn't apply to strings.
