### ISSUE TITLE
Please use constructors instead of factories

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-temporal#32]
It's generally an antipattern in JavaScript to have classes that are not constructible, but instead somehow the browser magically creates them when you use special factory functions. I don't understand the motivation for deviating from the normal pattern and doing `temporal.createTime()` instead of `new PlainTime()`.

**Comment by maggiepint** [comment]
Had a long conversation with @bterlson on this one, but in general we're coming back around to public constructors.

If we were to do non-constructable it's because the constructor for ZonedInstant is potentially a mess if you allow all the date parts, and in general people have no idea what they are doing when they construct the types. The factory functions provide a more clear API.

**Comment by domenic** [comment]
What do you see as the difference between factories and constructors? Both can provide the same API, so I don't see how it's possible for factories to be more clear.

**Comment by mj1856** [comment]
Well, we can name a factory function to describe the intent of the the creator, rather than than the type being created.

As currently spec'd:
```js
let dt = temporal.createDateTime(year, month, day, hour, minute);

let d = new temporal.PlainDate(year, month, day);
let t = new temporal.PlainTime(hour, minute);
let dt = new temporal.PlainDateTime(d, t);
```

Sure, we could change the constructor for `PlainDateTime` to look like the factory, but then we'd not be able to offer the existing constructor.  At least, not without the sort of messy type checking Moment deals with.

`ZonedInstant` is a bigger mess, as we really want people to create these through the chain of:

```js
let zi = temporal.createDateTime(year, month, day, hour, minute).withZone(timeZone);
```

I wouldn't want to support two constructors of `ZonedInstant`, as in:
```js
let zi = new temporal.ZonedInstant(year, month, day, hour, minute, timeZone);
let zi = new temporal.ZonedInstant(instant, timeZone);
```

Ultimately, I think having the top-level module `temporal` allows us to guide people down a fluent path of sensible APIs.  Yes, I agree that we must make them constructible, but IMHO, the constructors are more of a necessary evil than the golden path.

I'm open to having my mind changed on this point though. 😉

**Comment by domenic** [comment]
I'd suggest just using the signatures that you currently envision as factory functions, as the sole constructor signatures.

**Comment by mj1856** [comment]
So that would preclude `new temporal.PlainDateTime(date, time)`.  One could still `date.withTime(time)` or `time.withDate(date)`.  Do you think that is good enough?

**Comment by domenic** [comment]
I do, yes.

**Comment by mj1856** [comment]
Ok, I'll discuss with @maggiepint and unless there are objections then we'll remove the top-level factory functions and change the constructor of `PlainDateTime`.  I think the other constructors are ok as-is.

Now that I think through the case with `ZonedInstant` more, I think most of the arguments were clearer with the `ZonedDateTime` example.  Now changed to `ZonedInstant`, it avoids some of the mess.

**Comment by gilmoreorless** [comment]
Off the top of my head, a compromise solution to replace @mj1856's shorter `PlainDateTime` constructor could be `PlainDateTime.from(PlainDate, PlainTime)` (inspired by `Array.from()`, although the multiple-parameter format is more like `Array.of()`).

```js
let d = new temporal.PlainDate(year, month, day);
let t = new temporal.PlainTime(hour, minute);
let dt = temporal.PlainDateTime.from(d, t);
```

**Comment by maggiepint** [comment]
For the sake of cleanliness, I'm going to close this issue. We moved to constructors.
