### ISSUE TITLE
Require that the set of (built-in) calendars for Temporal equals the set supported by Intl

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-temporal#541]
Cross-reference: https://github.com/tc39/ecma402/issues/395#issuecomment-591266515

**Comment by ptomato** [comment]
I have a draft for this in https://github.com/tc39/proposal-temporal/compare/541-available-calendars-and-time-zones?expand=1

It brings in the definitions of AvailableTimeZones and AvailableCalendars from the Intl.Enumeration proposal, but slightly reworded so that they make sense as a 262 operation that gets overridden in 402.
It's currently blocked on resolving https://github.com/tc39/proposal-intl-enumeration/issues/37, but this should be the approximate shape of the solution.
