### ISSUE TITLE
Does the time zone or calendar count as an exotic internal slot?

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-temporal#786]
See some discussion here:

https://github.com/tc39/proposal-intl-segmenter/issues/96#issuecomment-661008571

@littledan

**Comment by ljharb** [comment]
That's not a rule I'm aware of; `Promise.resolve`, for example, access internal slots, as does every regex-taking String prototype method.

**Comment by justingrant** [comment]
> Temporal does not introduce any undeniables.

What's an "undeniable" ?

**Comment by ljharb** [comment]
@justingrant a "deniable" is something that first-run code is able to deny access to, in later-run code.

**Comment by justingrant** [comment]
What's an example of an undeniable?  And how does a "deniable" actually do the denying?  Via monkeypatching?  Also, is "deniability" an attribute of a type or of an instance?

While I'm asking naive questions, what makes an internal slot "exotic" vs. "non-exotic" ?  And what does "exotic" mean in this context?

BTW, I'm asking all these questions to try to understand three things: 

1. Is it OK for `LocalDateTime` to have an `absolute` object-valued property?  This case is subtly different from `timeZone` and `calendar` properties because there's no "custom `Absolute`" protocol like we have for calendars and time zones, so there's no need to store or create an `Absolute` object until a user asks for it.
2. Can the storage for that `absolute` property be lazy-initialized (from an `EPOCH_NANSECONDS` internal slot) so that clients don't have to pay for the object if they don't use the property?
3. Where should this object be stored?  Internal slot?  Own data prop?

**Comment by littledan** [comment]
@ljharb This was raised in an SES meeting; I don't know how widely it's been communicated. Maybe we should consider this in the context of the "documenting invariants" effort (cc @codehag ).

The story for `Promise.resolve` was that it maintains *practical* Proxy transparency via wrapping it as a thenable.

We could maintain "practical transparency" in Temporal by restoring the implicit `from` call to arguments to `compare` and `difference`, which I previously advocated for the removal of. (I'd be OK with reverting this decision if we have a strong reason to.)

@justingrant My answer your questions:
1. Yes
2. Yes, but would this really be observable? Presumably we will want implementations to be able to lazily allocate the Calendar instances as well, and avoid allocating TimeZone objects that are just used in a transitory way, right?
3. Internal slots are appropriate for this, so that the specification and implementation can rely on appropriate invariants for the algorithms (that no one else has messed with this property).

**Comment by ljharb** [comment]
Certainly if something’s going to affect the design of a proposal, it needs to be precisely describable :-) slots are currently accessed by both prototype and static methods, and on both the receiver and arguments, on every builtin type besides Error, all over the language, and I’m not aware of an organizing principle like the one suggested here.

**Comment by justingrant** [comment]
@littledan 

> Yes, but would this lazy allocation really be observable?

What does "observable" mean in this context?  I assume that the answer is "no, it would not be observable" but want to make sure that I know what you mean before being sure. 

> Presumably we will want implementations to be able to lazily allocate the Calendar instances as well

Does this mean that Date, DateTime, YearMonth, and MonthDay would all gain a CALENDAR_ID slot?  And that every usage of `GetSlot(this, CALENDAR)` would be replaced with a call to a lazy-init method like this?
```js
function getCalendar(o) {
  const current = GetSlot(o, CALENDAR);
  if (current === undefined) {
    const newValue = new CALENDAR(GetSlot(o, CALENDAR_ID));
    SetSlot(o, CALENDAR_ID, newValue);
    return newValue;
  } else {
    return current;
  }
}
```

> > 1. Is it OK for `LocalDateTime` to have an `absolute` object-valued property?  This case is subtly different from `timeZone` and `calendar` properties because there's no "custom `Absolute`" protocol like we have for calendars and time zones, so there's no need to store or create an `Absolute` object until a user asks for it.
> 1. Yes, this seems fine to me.

Does this imply that the changes proposed in #724 would also be OK to lazy-init?

**Comment by littledan** [comment]
By "observable" I mean, is it possible for a JavaScript program to detect the difference between a lazy and eager allocation implementation? I suspect that no JS program could tell the difference, meaning the spec could be written either way, and the difference is considered "editorial".

**Comment by littledan** [comment]
@ljharb I agree that if someone wants all JS proposals to follow certain rules, it would be best to propose those rules to the committee.

**Comment by ptomato** [comment]
Is this question sufficiently answered that we could close the issue?

**Comment by justingrant** [comment]
If we close it, it'd be great (for future readers like me who barely understand this issue) to include a summary of the actual criteria for what should and shouldn't be put into slots, and how those criteria relate to both Temporal and user-defined calendar and timezone objects.

**Comment by ptomato** [comment]
I think a good summary from the Temporal meeting today is that we cannot:
- have functionality that exposes internal slots directly (but it is OK to have readonly properties that return the value stored in an internal slot of `this`)
- produce observable effects on builtin objects (like the legacy RegExp properties)

I will close this issue for now but please correct me if the above is wrong! I don't feel that I have a 100% understanding of the problem either.

**Comment by ljharb** [comment]
@ptomato what do you mean by "exposes internal slots directly"?

**Comment by ptomato** [comment]
e.g. a hypothetical `getDateValueInternalSlotOfLegacyDate()` that returns whatever is in the [[DateValue]] slot of a Date object.

**Comment by ptomato** [comment]
(although [`Date.prototype.getTime` does that](https://tc39.es/ecma262/#sec-date.prototype.gettime) with the only difference being that it operates on `this`, so maybe I'm wrong here)

**Comment by ljharb** [comment]
Indeed - the majority of internal slots are exposed for reading in this way; some are exposed for writing, like with `Date.prototype.setTime`. The entire purpose of internal slots is to contain information that is core to the essence of what an object is, so that some mechanism can expose it or branch on it in an observable way.

**Comment by ByteEater-pl** [comment]
> What's an example of an undeniable?

@justingrant, the original value of `Array` (the function, constructor of Array objects) is a good example. Even if you tamper with `Array`, the code running later in the same Realm can obtain it using just syntax: `[].constructor`. On the other hand, access to random numbers can be effectively denied by first executing `delete Math.random`.
