### ISSUE TITLE
Proposal: we need a first-class ZonedDateTime!

### ISSUE THREAD

**Issue by burkenyo** [tc39/proposal-temporal#804]
This API is incomplete without a ZonedDateTime (or similar class). Similar to Java’s ZonedDateTime, this class would store a DateTime and TimeZone together, and would thus correspond 1-1 with an Absolute (except possibly around time zone shifts) while preserving time zone info.

**Comment by justingrant** [comment]
Hi @burkenyo - We will be adding such a type soon. See #700. That proposal is slightly out of date because we made a few decisions today:
* removing the `durationKind` option from `plus`, `minus` and `difference`, and removing the `calculation` option from `compare`.  Instead, users will convert to `DateTime` or `Absolute` and do the math there. 
* Likely removing the `.absolute` property getter in favor of a `toAbsolute()` method, and likely removing `absolute` as a property accepted by `from()` and `with()`.  I'm working through the implications of making this change. 

I'm in the process of updating that proposal to reflect current consensus.  Hope to have the changes done today.  

Other than those two things, #700 should be pretty current. Feedback appreciated!

I'm going to close this issue in favor of #700.
