### ISSUE TITLE
calendar.dateTimeFromFields

### ISSUE THREAD

**Issue by ryzokuken** [tc39/proposal-temporal#882]
Is it a good idea to allow `calendar.dateTimeFromFields` similar to `calendar.dateFromFields`?

/cc @Ms2ger @ptomato

**Comment by ptomato** [comment]
We used to have this but @sffc and I had discussed removing it because it does exactly the same conversion as `dateFromFields` (only difference is adding time fields to the DateTime object without doing any conversion.) It's just an opportunity for bugs to creep in if the logic in the two functions is different. However, we will need to add it again (as well as `timeFromFields`) if #522 is reconsidered.

**Comment by ptomato** [comment]
We do need this in order to implement the Ethiopian calendar, but I guess we can fold it into #522.

**Comment by sffc** [comment]
When we add `dateTimeFromFields`, there should be a default implementation such that you can implement only `dateFromFields` and not have to touch the time portion if your custom calendar doesn't deal with time.
