### ISSUE TITLE
Should `difference`'s default largestUnit be more consistent across types?

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#919]
Currently Temporal types have these defaults for `largestUnit`: 

* Time: `'hours'`
* Absolute: `'seconds'`
* YearMonth: `'years'`
* Date: `'days'`
* DateTime: `'days'`
* LocalDateTime: `'hours'` (because days can be different lengths in different time zones, cross-timezone difference with days or larger will throw. Therefore the default is hours because it will never throw.)  

That's a lot of variation!  Would it make sense to coalesce at least some of these defaults?

**Comment by ptomato** [comment]
Meeting, Sept. 18: The defaults are the way they are for a reason, so we'll keep the status quo here.
- Time: hours is the largest possible unit, and is non-lossy.
- Instant: seconds is the largest non-lossy unit.
- YearMonth: years is the largest possible unit (and is non-lossy for this type.)
- Date: days is the largest non-lossy unit.
- DateTime: days is the largest non-lossy unit.
- LocalDateTime: hours is the largest non-lossy unit. It's unfortunate that we can't have days be the largest non-lossy units like the other types, but because of time zones we can't.
