### ISSUE TITLE
calendar.id vs. timeZone.name

### ISSUE THREAD

**Issue by justingrant** [tc39/proposal-temporal#920]
Calendar has an `id` property while TimeZone has a `name` property. 

Any reason why both properties can't use the same name?  It'd be one less inconsistency for new users to learn.

**Comment by ptomato** [comment]
Meeting, Sept. 18: Unanimous agreement that this should be consistent. The majority preferred `id` because it expresses that the string is machine-readable (while `name` might be understood to be something like "Central European Summer Time"). TZDATA unfortunately refers to it as NAME, but we consider `id` to be more appropriate within JS.
