### ISSUE TITLE
Sign is lost

### ISSUE THREAD

**Issue by Pavel-Husakouski** [tc39/proposal-temporal#929]
`Temporal.Duration.from('-P2DT12H').toString()`

Expected result `-P2DT12H` but actual result is `P2DT12H`

**Comment by justingrant** [comment]
@Pavel-Husakouski - Thanks for the bug report here too!  This is the same problem as #930: you're using an out-of-date version of the polyfill. The code above runs without an exception using the latest code built from the main branch.

_I'm copying my response from that issue below to help other users figure out how to test code on the latest builds._

If you want to see the latest behavior reflecting the latest PRs, go to any page in the Temporal documentation (e.g. https://tc39.es/proposal-temporal/docs), open browser devtools console, and run the code there.

Here's an example: 

![image](https://user-images.githubusercontent.com/277214/93803310-7e24f080-fbf9-11ea-8c8c-4627f39838bc.png)


I'm going to close this issue because it doesn't repro on latest builds. Feel free to re-open if you see this issue when running in any docs page.
