### ISSUE TITLE
Duration - exception when subtrahend is bigger than minuend

### ISSUE THREAD

**Issue by Pavel-Husakouski** [tc39/proposal-temporal#930]
`Temporal.Duration.from('P1D').minus(Temporal.Duration.from('P2D'))`

Expected result is `-P1D` 
Actual result `RangeError: negative values not allowed as duration fields`

**Comment by justingrant** [comment]
@Pavel-Husakouski - Thanks for the bug report!  In this case, you're using an out-of-date version of the polyfill. The code above runs without an exception using the latest code built from the main branch.

If you want to see the latest behavior reflecting the latest PRs, go to any page in the Temporal documentation (e.g. https://tc39.es/proposal-temporal/docs), open browser devtools console, and run the code there.

Here's an example: 

![image](https://user-images.githubusercontent.com/277214/93802908-ec1ce800-fbf8-11ea-87e8-0ce40c5bc109.png)

I'm going to close this issue because it doesn't repro on latest builds. Feel free to re-open if you see this issue when running in any docs page.
